apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ic-docker-registry
  namespace: ic-docker-registry
  annotations:
    author: "Andrej Schefer <andrej.schefer@igneos.cloud>"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - "{{DOCKER_REGISTRY_URL}}"
      secretName: ic-docker-registry-cert-tls
  rules:
    - host: "{{DOCKER_REGISTRY_URL}}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ic-docker-registry
                port:
                  number: 5000
