apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: ic-docker-registry
data:
  config.yml: |
    version: 0.1

    # HTTP settings: listen on :5000 without TLS
    http:
      addr: :5000
      # no 'tls:' section → HTTPS disabled

    # enable deletion of blobs
    storage:
      delete:
        enabled: true
      filesystem:
        rootdirectory: /var/lib/registry

    # optional: logging
    log:
      fields:
        service: registry
