apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: igneos-cloud-registry-pvc
  namespace: ic-docker-registry
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{PVC_Storage_Capacity}}"
