apiVersion: v1
kind: Service
metadata:
  name: ic-docker-registry
  namespace: ic-docker-registry
spec:
  type: NodePort
  selector:
    app: ic-docker-registry
  ports:
    - name: ic-docker-registry-port
      protocol: TCP
      port: 5000
      targetPort: 5000
