apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "{{CLUSTER_ISSUER_NAME}}"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "{{EMAIL}}"
    privateKeySecretRef:
      name: "{{CLUSTER_ISSUER_NAME}}-account"
    solvers:
      - http01:
          ingress:
            class: traefik
