name: Build Binaries on Merge

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Make builder.bash executable
      run: chmod +x ./builder.bash

    - name: Run builder.bash
      run: ./builder.bash

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: k3s-installer-binaries
        path: builds/
        retention-days: 7