apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k3s-prometheus
  namespace: monitoring
spec:
  replicas: 1
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      release: k3s
  resources:
    requests:
      memory: 400Mi
      cpu: 100m
